export const GET_NOTES_REQUEST = "GET_NOTES_REQUEST"
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS"
export const GET_NOTES_FAILURE = "GET_NOTES_FAILURE"

export const POST_NOTES_REQUEST = "POST_NOTES_REQUEST"
export const POST_NOTES_SUCCESS = "POST_NOTES_SUCCESS"
export const POST_NOTES_FAILURE = "POST_NOTES_FAILURE"

export const UPDATE_NOTES_REQUEST = "UPDATE_NOTES_REQUEST"
export const UPDATE_NOTES_SUCCESS = "UPDATE_NOTES_SUCCESS"
export const UPDATE_NOTES_FAILURE = "UPDATE_NOTES_FAILURE"

export const DELETE_NOTES_REQUEST = "DELETE_NOTES_REQUEST"
export const DELETE_NOTES_SUCCESS = "DELETE_NOTES_SUCCESS"
export const DELETE_NOTES_FAILURE = "DELETE_NOTES_FAILURE"